apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # Deploymane name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # The pod name
        image: nginx:latest # Get the nginx application from dockerhub
        ports:
        - containerPort: 80 #App Port
